# Generated by Django 5.1.1 on 2024-10-08 03:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("client_id", models.IntegerField(unique=True)),
                ("first_name", models.CharField(blank=True, max_length=255, null=True)),
                ("last_name", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "middle_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("gender", models.CharField(blank=True, max_length=10, null=True)),
                ("source", models.CharField(blank=True, max_length=255, null=True)),
                ("phone", models.CharField(blank=True, max_length=20, null=True)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("status", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "credit_status",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("other_details", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
                ("language", models.CharField(blank=True, max_length=10, null=True)),
                ("uuid", models.UUIDField(blank=True, null=True, unique=True)),
            ],
            options={
                "verbose_name": "Клиент",
                "verbose_name_plural": "Клиенты",
            },
        ),
        migrations.CreateModel(
            name="PotentialClient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("client_id", models.IntegerField(unique=True)),
                ("phone", models.CharField(blank=True, max_length=20, null=True)),
                ("additional_info", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField()),
                ("updated_at", models.DateTimeField()),
                ("contract_id", models.CharField(blank=True, max_length=50, null=True)),
                ("external_data", models.JSONField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Потенциальный клиент",
                "verbose_name_plural": "Потенциальные клиенты",
            },
        ),
        migrations.CreateModel(
            name="Passport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("passport_number", models.CharField(max_length=50)),
                ("issue_date", models.DateField()),
                ("expiry_date", models.DateField()),
                ("issuing_authority", models.CharField(max_length=255)),
                ("birth_date", models.DateField()),
                ("place_of_birth", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
                (
                    "client",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="passports",
                        to="clients.client",
                    ),
                ),
            ],
            options={
                "verbose_name": "Паспорт",
                "verbose_name_plural": "Паспорта",
            },
        ),
    ]
