# Generated by Django 5.1.1 on 2024-10-08 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0002_client_other1_client_other2_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="client_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="client",
            name="uuid",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="passport",
            name="created_at",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="passport",
            name="updated_at",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
