# Generated by Django 5.1.1 on 2024-10-08 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0003_alter_client_client_id_alter_client_uuid_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="uuid",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
