# Generated by Django 5.1.1 on 2024-10-08 17:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0004_alter_client_uuid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="passport",
            name="client",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="passports",
                to="clients.client",
            ),
        ),
    ]
