# Generated by Django 5.1.1 on 2024-10-08 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0005_alter_passport_client"),
    ]

    operations = [
        migrations.AlterField(
            model_name="passport",
            name="birth_date",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="passport",
            name="expiry_date",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="passport",
            name="issue_date",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
