# Generated by Django 5.1.1 on 2024-10-09 08:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0007_telegramuser_alter_client_client_id_telegramuserlog"),
    ]

    operations = [
        migrations.CreateModel(
            name="StashUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="clients.telegramuser",
                    ),
                ),
            ],
            options={
                "verbose_name": "Пользователь Stash",
                "verbose_name_plural": "Пользователи Stash",
            },
        ),
    ]
