# Generated by Django 5.1.1 on 2024-10-10 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0008_stashuser"),
    ]

    operations = [
        migrations.DeleteModel(
            name="StashUser",
        ),
    ]
