# Generated by Django 5.1.1 on 2024-10-10 06:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0009_delete_stashuser"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="client_id",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="ID клиента"
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="created_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Дата создания"
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="credit_status",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Статус кредита"
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="email",
            field=models.EmailField(
                blank=True, max_length=254, null=True, verbose_name="Почта клиента"
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="first_name",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Фамилия клиента"
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="gender",
            field=models.CharField(
                blank=True, max_length=10, null=True, verbose_name="Пол клиента"
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="language",
            field=models.CharField(
                blank=True, max_length=10, null=True, verbose_name="Язык клиента"
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="last_name",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Имя клиента"
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="middle_name",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Отчество клиента"
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="other1",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Дополнительная информация 1",
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="other2",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Дополнительная информация 2",
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="other_details",
            field=models.JSONField(
                blank=True, null=True, verbose_name="Дополнительные детали"
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="phone",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="Телефон клиента"
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="source",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Источник клиента"
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="status",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Статус клиента"
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="updated_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Дата обновления"
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="uuid",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="UUID клиента"
            ),
        ),
        migrations.AlterField(
            model_name="passport",
            name="birth_date",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Дата рождения"
            ),
        ),
        migrations.AlterField(
            model_name="passport",
            name="client",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="passports",
                to="clients.client",
                verbose_name="Клиент",
            ),
        ),
        migrations.AlterField(
            model_name="passport",
            name="created_at",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Дата создания"
            ),
        ),
        migrations.AlterField(
            model_name="passport",
            name="expiry_date",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Дата окончания"
            ),
        ),
        migrations.AlterField(
            model_name="passport",
            name="issue_date",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Дата выдачи"
            ),
        ),
        migrations.AlterField(
            model_name="passport",
            name="issuing_authority",
            field=models.CharField(max_length=255, verbose_name="Кем выдан"),
        ),
        migrations.AlterField(
            model_name="passport",
            name="passport_number",
            field=models.CharField(max_length=50, verbose_name="ИИН"),
        ),
        migrations.AlterField(
            model_name="passport",
            name="place_of_birth",
            field=models.CharField(max_length=255, verbose_name="Место рождения"),
        ),
        migrations.AlterField(
            model_name="passport",
            name="updated_at",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Дата обновления"
            ),
        ),
        migrations.AlterField(
            model_name="potentialclient",
            name="additional_info",
            field=models.JSONField(
                blank=True, null=True, verbose_name="Дополнительная информация"
            ),
        ),
        migrations.AlterField(
            model_name="potentialclient",
            name="client_id",
            field=models.IntegerField(unique=True, verbose_name="ID клиента"),
        ),
        migrations.AlterField(
            model_name="potentialclient",
            name="contract_id",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="ID договора"
            ),
        ),
        migrations.AlterField(
            model_name="potentialclient",
            name="created_at",
            field=models.DateTimeField(verbose_name="Дата создания"),
        ),
        migrations.AlterField(
            model_name="potentialclient",
            name="external_data",
            field=models.JSONField(
                blank=True, null=True, verbose_name="Дополнительные данные"
            ),
        ),
        migrations.AlterField(
            model_name="potentialclient",
            name="phone",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="Телефон клиента"
            ),
        ),
        migrations.AlterField(
            model_name="potentialclient",
            name="updated_at",
            field=models.DateTimeField(verbose_name="Дата обновления"),
        ),
        migrations.AlterField(
            model_name="telegramuser",
            name="approved",
            field=models.BooleanField(default=False, verbose_name="Номер имеем"),
        ),
        migrations.AlterField(
            model_name="telegramuser",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Дата создания"),
        ),
        migrations.AlterField(
            model_name="telegramuser",
            name="first_name",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Имя"
            ),
        ),
        migrations.AlterField(
            model_name="telegramuser",
            name="last_name",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Фамилия"
            ),
        ),
        migrations.AlterField(
            model_name="telegramuser",
            name="phone_number",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="Номер телефона"
            ),
        ),
        migrations.AlterField(
            model_name="telegramuser",
            name="telegram_id",
            field=models.CharField(
                max_length=50, unique=True, verbose_name="Telegram ID"
            ),
        ),
        migrations.AlterField(
            model_name="telegramuser",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
        ),
        migrations.AlterField(
            model_name="telegramuser",
            name="username",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Юзер Нейм"
            ),
        ),
        migrations.AlterField(
            model_name="telegramuserlog",
            name="action",
            field=models.TextField(verbose_name="Действие"),
        ),
        migrations.AlterField(
            model_name="telegramuserlog",
            name="timestamp",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Время"),
        ),
        migrations.AlterField(
            model_name="telegramuserlog",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="logs",
                to="clients.telegramuser",
                verbose_name="Пользователь Telegram",
            ),
        ),
    ]
